# Generated by Django 5.0.6 on 2024-07-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
